const questions = [
  {
    id: "#36",
    title: "#36 Human Remains",
    text: "Human remains are a fundamental part of the archaeological record, offering unique insights into the lives of individuals and populations in the past. Like many archaeological materials, human remains require distinctive and specialized methods of recovery, analysis, and interpretation, while technological innovations and the accumulation of expertise have enabled archaeologists to extract ever greater amounts of information from assemblages of skeletal material. Alongside analyses of new finds, these advances have consistently thrown new light on existing collections of human remains in museums, universities and other institutions. Given the powerful emotional, social and religious meanings attached to the dead body, it is perhaps unsurprising that human remains pose a distinctive set of ethical questions for archaeologists.\nWith the rise of indigenous rights movements and the emergence of post-colonial nations, the acquisition and ownership of human remains became a divisive and politically loaded issue. It became increasingly clear that many human remains in museum collections around the world represented the traces of colonial exploitation and discredited pseudo-scientific theories of race. In the light of these debates and changing attitudes, some human remains were returned or repatriated to their communities of origin, a process which continues to this day. Recently a new set of challenges to the study of human remains has emerged from a rather unexpected direction: the British government revised its interpretation of nineteenth-century burial legislation in a way that would drastically curtail the ability of archaeologists to study human remains of any age excavated in England and Wales. This paper examines these extraordinary events and the legal, political and ethical questions that they raise."
  },
  {
    id: "#39",
    title: "#39 Malaysia Tourism",
    text: "Malaysia is also launching its biggest ever tourism campaign in an effort to lure 20 million visitors here this year. Tourism is the Southeast Asian nation's second-largest source of foreign exchange after exports. Malaysia is one of the most pleasant, hassle-free countries to visit in Southeast Asia. Aside from its gleaming 21st century glass towers, it boasts some of the most superb beaches, mountains and national parks in the region.\nAny tourist itinerary would have to begin in the capital, Kuala Lumpur, where you will find the Petronas Twin Towers, which once comprised the world's tallest buildings and now hold the title of second-tallest. Both the 88-story towers soar 1,480 feet high and are connected by a sky-bridge on the 41st floor. The limestone temple Batu Caves, located 9 miles north of the city, have a 328-foot-high ceiling and feature ornate Hindu shrines, including a 141-foot-tall gold-painted statue of a Hindu deity. To reach the caves, visitors have to climb a steep flight of 272 steps. In Sabah state on Borneo island not to be confused with Indonesia's Borneo you'll find the small mushroom-shaped Sipadan island, off the coast of Sabah, rated as one of the top five diving sites in the world. Sipadan is the only oceanic island in Malaysia, rising from a 2,300-foot abyss in the Celebes Sea. You can also climb Mount Kinabalu, the tallest peak in Southeast Asia, visit the Sepilok Orang Utan Sanctuary, go white-water rafting and catch a glimpse of the bizarre proboscis monkey, a primate found only in Borneo with a huge pendulous nose, a characteristic pot belly and strange honking sounds.\nWhile you're in Malaysia, consider a trip to Malacca. In its heyday, this southern state was a powerful Malay sultanate and a booming trading port in the region. Facing the Straits of Malacca, this historical state is now a place of intriguing Chinese streets, antique shops, old temples and reminders of European colonial powers. Another interesting destination is Penang, known as the Pearl of the Orient. This island off the northwest coast of Malaysia boasts of a rich Chinese cultural heritage, good food and beautiful beaches."
  },
  {
    id: "#40",
    title: "#40 Small Wars",
    text: "In such an environment, warfare is no longer purely directed against the military potential of adversarial states. It is rather directed at infiltrating all areas of their societies and threatening their existences. The comparatively easy access to weapons of mass destruction, in particular low-cost biological agents, is of key concern. Both governmental and non-governmental actors prefer to use force in a way that can be characterized as \"unconventional\" or also as \"small wars\". War waged according to conventions is an interstate phenomenon. The \"small war\" is the archetype of war, in which the protagonists acknowledge no rules and permanently try to violate what conventions do exist. The protagonists of the \"small war\" observe neither international standards nor arms control agreements. They make use of territories where they do not have to fear any sanctions because there is no functioning state to assume charge of such sanctions or because the state in question is too weak to impose such sanctions. This type of war does not provide for any warning time. It challenges not only the external security of the nation states and international community, but also their internal safety."
  },
  {
    id: "#180",
    title: "#180 New Women",
    text: "In the 1890s there was a positive media feeding frenzy in Britain and in North America both defending and attacking the \"New Woman\". Some commentators have dated the beginning of this very precisely, from March 1894, when the British novelist Sarah Grand first used the label in an article in the North American Review. Grand hailed the New Woman as one who had at last \"solved the problem and proclaimed for herself what was wrong with Home-is-the-Woman's-Sphere, and prescribed the remedy\". Other commentators have seen the term growing out of and crystallizing a steadily swelling debate over several decades about the position of women of the middle classes, their scope for independence, the implications of the access to secondary and higher education which they were beginning to secure, and the legal, financial, social and psychological constraints imposed upon them by marriage.\nThe latter is a more fruitful reading, allowing as it does a consideration of a wider literature over a longer period. Although the structure of the English state and political system favored single-issue campaigns, those involved were often associated, even though their primary targets differed, and they were collectively known to contemporaries as \"the women's movement\"."
  },
  {
    id: "#197",
    title: "#197 Bertrand Russell",
    text: "Russell was arguably the greatest philosopher of the 20th century and the greatest logician since Aristotle. Analytic philosophy, the dominant philosophy of the twentieth century, owes its existence more to Russell than to any other philosopher. And the system of logic developed by Russell and A.N. Whitehead, based on earlier work by Dedekind, Cantor, Frege, and Peano, broke logic out of its Aristotelian straitjacket. He was also one of the century's leading public intellectuals and won the Nobel Prize for Literature in 1950 \"in recognition of his varied and significant writings in which he champions humanitarian ideals and freedom of thought.\"\nRussell was involved, often passionately, in numerous social and political controversies of his time. For example, he supported suffragists, free thought in religion and morals, and world government; he opposed World War I and the Vietnam War, nationalism, and political persecution. He was jailed in 1918 for anti-war views and in 1961 for his anti-nuclear weapons stance.\nHe was married 4 times and had 3 children. With Dora Russell, he founded the experimental Beacon Hill School. He knew or worked with many of the most prominent figures in late 19th and 20th century philosophy, mathematics, science, literature, and politics. Active as a political and social critic until his end, Russell died in 1970 at the age of 97."
  },
  {
    id: "#222",
    title: "#222 Product Life Cycle",
    text: "The product life cycle has 4 very clearly defined stages, each with its characteristics that mean different things for businesses that are trying to manage the life cycle of their particular products.\nIntroduction Stage - This stage of the cycle could be the most expensive for a company launching a new product. The size of the market for the product is small, which means sales are low, although they will be increasing. On the other hand, the cost of things like research and development, consumer testing, and the marketing needed to launch the product can be very high, especially if it's a competitive sector.\nGrowth Stage - The growth stage is typically characterized by strong growth in sales and profits, and because the company can start to benefit from economies of scale in production, the profit margins, as well as the overall amount of profit, will increase. This makes it possible for businesses to invest more money in promotional activity to maximize the potential of this growth stage.\nMaturity Stage - During the maturity stage, the product is established and the aim for the manufacturer is now to maintain the market share they have built up. This is probably the most competitive time for most products and businesses need to invest wisely in any marketing they undertake. They also need to consider any product modifications or improvements to the production process which might give them a competitive advantage.\nDecline Stage - Eventually, the market for a product will start to shrink, and this is what's known as the decline stage. This shrinkage could be due to the market becoming saturated (i.e. all the customers who will buy the product have already purchased it), or because the consumers are switching to a different type of product. While this decline may be inevitable, it may still be possible for companies to make some profit by switching to less-expensive production methods and cheaper markets."
  },
  {
    id: "#498",
    title: "#498 Origin of Species",
    text: "In 1837, at the age of 28, Darwin wrote \"Species Change\" in one of his notebooks, which was the earliest record of his evolutionary ideas. Prior to this, he had sailed around the world for 5 years on the HMS Beagle, observing numerous signs that species were not fixed in South America, Oceania, and other places. After returning to England, he wrote \"Cuidado\" (meaning \"be careful\" in Spanish) in another notebook, realizing that the theory of evolution was a radical and dangerous view, and that there was insufficient evidence to make it public at that time.\nOver the next 20 years, Darwin continuously accumulated a vast amount of data and first presented his views to a small circle of scientists. It was not until 1859, when \"On the Origin of Species\" was published, that his ideas became accessible to the general readership, causing a great sensation. The first edition of 1,250 copies sold out on the day of publication, and the circulation reached 4,250 copies within a year, receiving both praise from the scientific community and fierce criticism from the religious community and conservative forces.\nTo this day, \"On the Origin of Species\" remains one of the most important works in human history, and one of the few works that still has scientific value more than 150 years after its publication. Darwin was well aware that his work was only the beginning. He wrote in the book: \"In the distant future, I see open fields for far more important research.\""
  },
  {
    id: "#1",
    title: "#1 2014 Olympics",
    text: "11 February 2009 - Major athletic events around the globe - from the 2014 Sochi Olympics to an annual powerboat race in Norwegian fjords - are striving to neutralize their carbon footprint as part of a world-wide climate network, the United Nations Environment Programme (UNEP) said today.\nThe sporting events are the latest participants to join the network, and are particularly important for inspiring further global action on the environment, said Achim Steiner, UNEP Executive Director.\n\"It is, therefore, heartening that this passion for excellence increasingly encompasses environmental performance, with sporting organizations raising the bar ever higher at each and every tournament,\" he added.\nOrganizers of the 2014 Sochi Olympic and Paralympic Winter Games to be held in a unique natural setting between the shores of the Black Sea and the soaring snow-capped Caucasus Mountains - say they will put an estimated $1.75 billion into energy conservation and renewable energy.\nThat investment will be dedicated to improving transport infrastructure and offsetting greenhouse gas emissions from the use of electricity, air travel and ground transportation, the reforestation of Sochi National Park and the development of green belts in the city."
  },
  {
    id: "#10",
    title: "#10 Australian Indigenous Food",
    text: "In its periodic quest for culinary identity, Australia automatically looks to its indigenous ingredients, the foods that are native to this country. \"There can be little doubt that using an indigenous product must qualify a dish as Australian\", notes Stephanie Alexander. Similarly, and without qualification, states that a uniquely Australian food culture can only be based upon foods indigenous to this country.\nHowever, as Craw remarks, proposing Australian native foods as national symbols relies more upon their association with nature and geographic origin than on common usage. Notwithstanding the lack of justification for the premise that national dishes are, of necessity, founded on ingredients native to the country after all, Italy's gastronomic identity is tied to the non-indigenous tomato, Thailand's to the non-indigenous chili the reality is that Australians do not eat indigenous foods in significant quantities. The exceptions are fish, crustaceans and shellfish from oceans, rivers and lakes, most of which are unarguably unique to this country. Despite valiant and well-intentioned efforts today at promoting and encouraging the consumption of native resources, bush foods are not harvested or produced in sufficient quantities for them to be a standard component of Australian diets, nor are they generally accessible. Indigenous foods are less relevant to Australian identity today than lamb and passionfruit, both initially imported and now naturalized."
  },
  {
    id: "#15",
    title: "#15 Children Allowance",
    text: "Many people who have written on the subject of allowances say it is not a good idea to pay your child for work around the home. These jobs are a normal part of family life. Paying children to do extra work around the house, however, can be useful. It can even provide an understanding of how a business works.\nAllowances give children a chance to experience the things they can do with money. They can share it in the form of gifts or giving to a good cause. They can spend it by buying things they want. Or they can save and maybe even invest it. Saving helps children understand that costly goals require sacrifice: you have to cut costs and plan for the future. Requiring children to save part of their allowance can also open the door to future saving and investing. Many banks offer services to help children and teenagers learn about personal finance. A savings account is an excellent way to learn about the power of compound interest. Compounding works by paying interest on interest. So, for example, one dollar invested at two percent interest for two years will earn two cents in the first year. The second year, the money will earn two percent of one dollar and two cents, and so on. That may not seem like a lot. But over time it adds up."
  },
  {
    id: "#19",
    title: "#19 Compulsory Reburial",
    text: "Human remains are a fundamental part of the archaeological record, offering unique insights into the lives of individuals and populations in the past. Recently a new set of challenges to the study of human remains has emerged from a rather unexpected direction: the British government revised its interpretation of nineteenth-century burial legislation in a way that would drastically curtail the ability of archaeologists to study human remains of any age excavated in England and Wales. This paper examines these extraordinary events and the legal, political and ethical questions that they raise.\nIn April 2008 the British government announced that, henceforth, all human remains archaeologically excavated in England and Wales should be reburied after a two-year period of scientific analysis. Not only would internationally important prehistoric remains have to be returned to the ground, removing them from public view, but also there would no longer be any possibility of long-term scientific investigation as new techniques and methods emerged and developed in the future. Thus, while faunal remains, potsherds, artifacts and environmental samples could be analyzed and re-analyzed in future years, human remains were to be effectively removed from the curation process. Archaeologists and other scientists were also concerned that this might be the first step towards a policy of reburying all human remains held in museum collections in England and Wales including prehistoric, Roman, Saxon, Viking and Medieval as well as more recent remains."
  },
  {
    id: "#30",
    title: "#30 Geothermal Energy",
    text: "What is the solution for nations with increasing energy demands, hindered by frequent power cuts and an inability to compete in the international oil market? For East Africa at least, experts think geothermal energy is the answer. More promising still, the Kenyan government and international investors seem to be listening. This is just in time according to many, as claims of an acute energy crisis are afoot due to high oil prices, population spikes and droughts. Currently over 60% of Kenya's power comes from hydroelectric sources but these are proving increasingly unreliable as the issue of seasonal variation is intensified by erratic rain patterns. Alternative energy sources are needed, and the leading energy supplier in Kenya, Kenya Electricity Generating Company, hopes to expand its geothermal energy supply from 13% to 25% of its total usage by 2020. The potential of geothermal energy in the region was first realised internationally by the United Nations Development Program, when geologists observed thermal anomalies below the East African Rift system. Locals have been utilising this resource for centuries; using steam vents to create the perfect humidity for greenhouses, or simply to enjoy a swim in the many natural hot lakes. Along the 6000 km of the rift from the Red Sea to Mozambique, geochemical, geophysical and heat flow measurements were made to identify areas suitable for geothermal wells. One area lies next to the extinct Olkaria volcano, within the Hell's Gate National Park, and sits over some of the thinnest continental crust on Earth. This is a result of the thinning of the crust by tectonic stretching, causing hotter material below the Earth's surface to rise, resulting in higher temperatures. This thin crust was ideal for the drilling of geothermal wells, reaching depths of around 3000 m, where temperatures get up to 342°C far higher than the usual temperature of 90°C at this depth. Water in the surrounding rocks is converted to steam by the heat. The steam can be used to drive turbines and produce electricity."
  },
  {
    id: "#34",
    title: "#34 Hookham",
    text: "The booksellers of Hookham and Carpenter (hereafter referred to only as Hookham) were located on New Bond Street in London, and their records span the most politically turbulent decade of the eighteenth-century the 1790's. Clients who frequented Hookham were primarily from the aristocratic or gentry classes. In fact, of Hookham's total buyers, 22% were aristocracy, and 35% of the aristocracy purchased novels. We can also confidently assume that untitled female customers were of gentry income because their addresses were primarily in London's fashionable 'West End'.\nHookham's ledgers not only reveal a dramatic increase in the proportion of female purchasers of novels by comparison to earlier studies of provincial women, but they also reveal a remarkable increase in the proportion of female purchases of novels authored by females. Such a marked increase illustrates that Hookham's leisured female customers were able to buy more novels.\nFurthermore, the fact that these female aristocrats and gentry have accounts under their own name, not their husbands, demonstrates the greater degree of agency and independence that these urban, moneyed women had relative to provincial women. However, because our study does not include an examination of male customers, we are very limited in what claims we can make about whether or not these women behaved according to the cliche that women were the predominant consumers of novels in the eighteenth-century.\nMoreover, while more disposable income and leisure time certainly account for the significant increase in female purchases of novels authored by women in the 1790s, this increase also strongly suggests a desire on the part of women readers to engage in this politically charged decade. Thus, novel-reading provided women readers with the means through which they were able to participate in the male-dominated world of politics. The latter part of our paper will more fully explore this hypothesis in the context of certain recent literary scholars claim that both Gothic and sentimental novels are actively engaged in political debate and discussion."
  },
  {
    id: "#35",
    title: "#35 House Mice",
    text: "According to new research, house mice (Mus musculus) are ideal biomarkers of human settlement as they tend to stow away in crates or on ships that end up going where people go. Where people go, so do mice, often stowing away in carts of hay or on ships. Despite a natural range of just 100 meters (109 yards) and an evolutionary base near Pakistan, the house mouse has managed to colonize every continent, which makes it a useful tool for researchers like Searle.\nUsing mice as a proxy for human movement can add to what is already known through archaeological data and answer important questions in areas where there is a lack of artifacts, Searle said.\nPrevious research conducted by Searle at the University of York supported the theory that Australian mice originated in the British Isles and probably came over with convicts shipped there to colonize the continent in the late 18th and 19th centuries. He came to the conclusion by using evolutionary techniques to analyze mitochondrial DNA, comparing modern-day mouse populations from Australia with those from their likely regional source in Western Europe. In the Viking study, he and his fellow researchers in Iceland, Denmark, and Sweden took it a step further, using ancient mouse DNA collected from archaeological sites dating from the 10th to 12th centuries, as well as modern mice. He is hoping to do just that in his next project, which involves tracking the migration of mice and other species, including plants, across the Indian Ocean, from South Asia to East Africa."
  },
  {
    id: "#42",
    title: "#42 Museology",
    text: "What is museology? A simple definition might be that it is the study of museums, their history and underlying philosophy, the various ways in which they have, in the course of time, been established and developed, their avowed or unspoken aims and policies, their educative or political or social role. More broadly conceived, such a study might also embrace the bewildering variety of audiences visitors, scholars, art lovers, children at whom the efforts of museum staff are supposedly directed, as well as related topics such as the legal duties and responsibilities placed upon (or incurred by) museums, perhaps even some thought as to their future. Seen in this light, museology might appear at first sight a subject so specialized as to concern only museum professionals, who by virtue of their occupation are more or less obliged to take an interest in it. In reality, since museums are almost, if not quite as old as civilization itself, and since the plethora of present-day museums embraces virtually every field of human endeavor - not just art, or craft, or science, but entertainment, agriculture, rural life, childhood, fisheries, antiquities, automobiles: the list is endless it is a field of enquiry so broad as to be a matter of concern to almost everybody."
  },
  {
    id: "#46",
    title: "#46 Office Environment",
    text: "The notion that office space has a role in promoting or inhibiting performance is backed up by solid research. A recent study conducted by Harvard University and Massachusetts General Hospital showed that improvements to the physical surroundings of workers impacted on productivity not just because the working environment was more attractive, but because the changes made employees feel cared for. A Swedish research paper revealed a strong link between the type of office an employee worked in and their overall job satisfaction and health. Various findings have emerged as a result of studies such as this. Pot plants and greenery can apparently have a real impact on psychological well-being. Those who work in a private room tend to be in better health than workers based in open-plan offices.\nSufficient light can reduce sickness among workers and increase productivity, and an attractive office can make workers feel more cared for and therefore more loyal to their company. Most of these points make good rational sense. But some companies aren't content simply to increase the health, productivity and contentment of their employees. Pioneers such as Google, Walt Disney and Dyson have tried to create offices that will do everything from promoting collaboration between workers to stimulating their creative juices. \"Environment, both physical and cultural, can make or break creativity.\" says Kursty Groves, author of I Wish I Worked There! A look inside the most creative spaces in business. Stimulating spaces expose the mind to a variety of stimuli planned or random In order to encourage people to think differently. Reflective spaces promote the filtering of information into the brain slowing it to make connections. An environment which encourages a team to build trust and to play freely is an essential ingredient for innovation."
  },
  {
    id: "#48",
    title: "#48 Online Teaching & Learning",
    text: "What makes teaching online unique is that it uses the internet, especially the World Wide Web, as the primary means of communication. Thus, when you teach online, you don't have to be someplace to teach. You don't have to lug your briefcase full of paper or your laptop to a classroom, stand at a lectern, scribble on a blackboard (or even use your high-tech, interactive classroom \"smart\" whiteboard), or grade papers in a stuffy room while your students take a test. You don't even have to sit in your office waiting for students to show up for conferences. You can hold \"office hours\" on weekends or at night after dinner. You can do all this while living in a small town in Wyoming or a big city like Bangkok, even if you are working for a college whose administrative office is located in Florida or Dubai. You can attend an important conference in Hawaii on the same day you teach your class in New Jersey, logging on from your laptop via the local café's wireless hotspot or your hotel room's high-speed network. Or you may simply pull out your smartphone to quickly check on the latest postings, email, or text messages from students.\nOnline learning offers more freedom for students as well. They can search for courses using the Web, scouring their institution or even the world for programs, classes, and instructors that fit their needs. Having found an appropriate course, they can enroll and register, shop for their books, read articles, listen to lectures, submit their homework assignments, confer with their instructors, and receive their final grades all online. They can assemble virtual classrooms, joining other students from diverse geographical locales, forging bonds and friendships not possible in conventional classrooms, which are usually limited to students from a specific geographical area."
  },
  {
    id: "#51",
    title: "#51 Paleolithic People",
    text: "The ways of life of Upper Paleolithic people are known through the remains of meals scattered around their hearths, together with many tools and weapons and the debris left over from their making. The people were hunter-gatherers who lived exclusively from what they could find in nature without practicing either agriculture or herding. They hunted the bigger herbivores, while berries, leaves, roots, wild fruit and mushrooms probably played a major role in their diet. Their hunting was indiscriminate, perhaps because so many animals were about they did not need to spare pregnant females or the young. In the cave of Enlene, for example, many bones of reindeer and bison fetuses were found. Apparently, upper Paleolithic people hunted like other predators and killed the weakest prey first. They did, however, sometimes concentrate on salmon runs and migrating herds of reindeer. Contrary to popular beliefs about cave man, upper Paleolithic people did not live deep inside caves. They rather chose the foot of cliffs, especially when an overhang provided good shelter. On the plains and in the valleys, they used tents made from hides of the animals they killed. At time, on the great Russian plains, they built huts with huge bones and tusks collected from skeletons of mammals. Men hunted mostly with spears, as the bow and arrow were probably not invented until the Magdalenian period that came at the end of the Upper Paleolithic. Tools and weapons, made out of wood or reindeer antlers, often had flint cutting edges."
  },
  {
    id: "#55",
    title: "#55 Plants Research",
    text: "Plants serve as the conduit of energy into the biosphere, provide food and materials used by humans, and shape our environment. According to Ehrhardt and Frommer, the three major challenges facing humanity in our time are food, energy, and environmental degradation. All three are plant related.\nAll of our food is produced by plants, either directly or indirectly via animals that eat them. Plants are a source of energy production. And they are intimately involved in climate change and a major factor in a variety of environmental concerns, including agricultural expansion and its impact on habitat destruction and waterway pollution.\nWhat's more, none of these issues are independent of each other. Climate change places additional stresses on the food supply and on various habitats. So, plant research is instrumental in addressing all of these problems and moving into the future. For plant research to move significantly forward, Ehrhardt and Frommer say technological development is critical, both to test existing hypotheses and to gain new information and generate fresh hypotheses. If we are to make headway in understanding how these essential organisms function and build the foundation for a sustainable future, then we need to apply the most advanced technologies available to the study of plant life, they say."
  },
  {
    id: "#72",
    title: "#72 Tree Rings",
    text: "Here's how tree ring dating, known to scientists as dendrochronology, works. If you cut a tree down today, it is straightforward to count the rings inwards, starting from the tree's outside. Hence the sequence of the rings in a tree cross-section is like a message in Morse code formerly used for sending telegraph messages; dot-dot-dash-dot-dash in the Morse code, wide-wide-narrow-wide-narrow in the tree ring sequence.\nActually, the tree-ring sequence is even more diagnostic and richer in information than the Morse code, because trees actually contain rings spanning much different width, rather than the Morse code choice between dot and dash.\nTree ring specialists (known as dendrochronologists) proceed by noting the sequence of wider and narrower rings in a tree cut down in a known recent year, and also noting the sequences in beams from trees cut down at various times in the past. In that way, dendrochronologists have constructed tree ring records extending back for thousands of years in some parts of the world. A bonus of dendrochronology is that the width and substructure of each ring reflect the amount of rain and the season at which the rain fell during that particular year. Thus, tree ring studies also allow one to reconstruct the past climate."
  },
  {
    id: "#81",
    title: "#81 Wright Brothers",
    text: "In 1903, Wilbur and Orville Wright, two brothers from Dayton, OH, became the first people to fly a heavier than air, power controlled machine, known as the Wright Flyer. This did not simply happen overnight. The brothers had been tinkering with the idea of flight off and on since childhood. They were mechanically inclined young men who were inspired by the efforts of others.\nIn 1878, the brothers' father, Milton Wright, brought home a rubber band powered toy helicopter. Designed by French aeronautical experimenter Alphonse Pénaud, this toy did not simply fall to the ground as expected. Rather it \"flew across the room till it struck the ceiling, where it fluttered awhile, and finally sank to the floor.\" Though the fragile toy soon broke, Wilbur and Orville never forgot it. They even attempted to build their own toy helicopters. In later years, Orville accredited this childhood toy as sparking their interest in flight.\nThroughout their lives, the brothers were involved in a variety of ventures to make money. But it wasn't until 1892, when they formed the Wright Cycle Company, finding a successful business that allowed spare time for other projects, to sell bicycles, that they found a successful business that also allowed them spare time for other projects. With the business doing rather well, the brothers also opened a repair shop and later began to manufacture bicycles.\nThough the business was going well, the brothers were restless. Their energies were focused by two 1896 events: the death of Otto Lilienthal and the successful unmanned launching of powered models by Samuel Langley; the death of Otto Lilienthal, the celebrated glider experimenter, in a flying accident, and the successful unmanned launching of powered models by Samuel Langley. The creativity and ingenuity of these two men were well and truly captured. Fortunately, the bicycle business provided funds and sharpened mechanical skills for their new interest, for unlike others in aviation, the Wrights were never financed by anyone. Furthermore, the repair and manufacture of bicycles sharpened the brothers' mechanical skills. In their construction of flying machines, Wilbur and Orville often used the same equipment and tools used in repairing bicycles. They conducted many of their scientific experiments in the backroom of their shop and most of the parts used in the first successful airplane were built there."
  },
  {
    id: "#88",
    title: "#88 Reading",
    text: "It might seem a little eccentric, but reviewing your work by reading it aloud can help to identify the woolliest areas. This works best if you perform your reading in a theatrical way, pausing at the commas and ends of sentences. If you run out of breath during a sentence, it is probably too long. You ought to be able to convert your writing into a speech in this way if it sounds too stilted and convoluted, perhaps you could rework these parts until they sound fluid. It is unlikely that your reader will be fooled by the idea that long words make you sound clever. Cluttering a sentence with too many complicated words can prevent its meaning from being understood at all. A short word is always preferable to a long one. Why should anyone choose the word erroneous over the word wrong in an essay? Usually, writers who employ more obscure words are trying to sound impressive but can appear pretentious. Direct words enable you to control what you are saying, and are not necessarily babyish, but the most appropriate ones for the job. When you read your writing aloud, you will notice that the key stress comes at the end of your sentence. It is, therefore, most effective to end with a short and emphatic word to secure your point. Try to resist the impulse to waffle at the end of your sentence by trailing off into qualifying clauses. It might be worth relocating the clause to the beginning of the sentence or losing it altogether if you feel that it adds little to its meaning. Your sentences might be the most grammatically perfect in the world, but still, cause your writing to sound wrong if you have misjudged its tone. A colloquial style, which uses slang and exclamations, is an inappropriately chatty tone for an essay. However, style can be equally jarring if your vocabulary is too formal or ambitious for its context. It is much more impressive to make complicated points using simple language and grammar."
  },
  {
    id: "#103",
    title: "#103 Silent Movies",
    text: "The 1920's movie-goers experience was largely dominated by silent movies but saw the introduction of synchronized sound. In the 1920's movie stars were really stars with huge salaries, the fashions and activities of the Hollywood greats echoed around the world and 100,000 people would gather in cities all over the world, including such diverse cities as London and Moscow, to greet Mary Pickford and Douglas Fairbanks when they toured of Europe. Early silent movies were often accompanied by live piano or organ music and provided enormous entertainment value to audiences captivated by the experience of watching moving pictures on the silver screen. Although there had been previous attempts to introduce sound, it wasn't until 1923 that a synchronized soundtrack was photographically recorded and printed on to the side of the strip of motion picture film and made it on to a commercially distributed movie. It would still be seven long years before talking pictures gained total supremacy and finally replaced the silent film era.\nThe first movie theatres were called Nickelodeons, and were very basic compared to the luxurious picture palaces that followed but what an aura of excitement, of laughter, fun and tears surrounded them! Before the introduction of movie soundtracks, movies were often accompanied by scripted music from a piano."
  },
  {
    id: "#113",
    title: "#113 Pre-service Teachers",
    text: "Each individual content-area course has a separate syllabus that highlights the specific technologies and pedagogy relevant to the content area. The technologies were selected after numerous meetings between methods and technology course instructors. After identifying the most appropriate technology, methods and technology course instructors co-developed their syllabi with projects spanning the two courses. Therefore, students learn about a specific technology in the technology course, and they integrate it in their practice teaching experiences within their methods course.\nIn a research collaboration with a methods area faculty member, the technology course instructor found that although preservice teachers know how to operate technology, they could not integrate it effectively within daily lesson plans and they were not able to envision the type of projects their students could develop. These findings influenced the technology course instructor to develop exemplary models of technology projects and pedagogy for each technology course section (i.e. content areas).\nFor example, a project was modeled to illustrate how students construct understanding of clouds using concept mapping within the science cohort. This project was supplemented by the instructor modeling effective teaching practices using concept mapping in the science classroom. The goal was to move the preservice teachers from focusing not only on the development of a final technology project in the course but encouraging them to think about successful integration in their future classrooms. These examples were placed online so the preservice teachers had access to them at all times in the development of their own projects for the technology course."
  },
  {
    id: "#162",
    title: "#162 Negotiation",
    text: "Negotiation is a common process in business to mainly solve business conflicts between both parties. Compromise is a basic negotiation state in which both parties give up something that they want in order to get something else they want more. Compromise usually occurs in unfair parties when there is a fixed pie to be divided up, and whatever on one side gets, the other side loses.\nIn compromise situations, neither side gets all of what they really want, but they each make concessions in order to reach an agreement that is acceptable to both. Both parties usually can reach a win-win situation through compromise. However, negotiation cannot resolve all the conflict if one party is unwilling to resolve the problem."
  },
  {
    id: "#168",
    title: "#168 Greenland Sharks",
    text: "An international team of scientists, including a physiologist from The University of Manchester, will head to the largest island in the world later this month to investigate the Greenland shark - believed to be the longest-lived vertebrate animal. Dr Holly Shiels, who is also a trustee of the Physiological Society, will be the only UK-based scientist on the expedition aboard the research vessel Sanna commissioned by the Greenland government. The purpose of the mission is to understand more about the Greenland shark, a top predator in the Arctic, which lives for more than 272 years - possibly more than 400. This extreme age was only revealed by scientists from Copenhagen last year and published in the journal Science. Little else is known about how the shark survives in the deep seas around the Arctic Circle. It is both a hunter and a scavenger and has been seen to feed on seals and been found with the remains of polar bears and whales in its stomach. It is also one of the largest species of shark - growing to about five-and-a-half metres, just a bit smaller than the great white. However, more information is required to ensure the species is adequately protected, as Dr Shiels explained: \"Greenland sharks are classified as data deficient,\" she said. \"This means that we don't know enough to put measures in place to protect them from over-fishing, pollution or climate change. This expedition has a broad range of expertise which means that we'll be able to take full advantage of any sharks that we discover.\""
  },
  {
    id: "#63",
    title: "#63 Language Teaching Approaches",
    text: "Over the years, language teachers have alternated between favoring teaching approaches that focus primarily on language use and those that focus on language forms or analysis. The alternation has been due to a fundamental disagreement concerning whether one learns to communicate in a second language by communicating in that language (such as in an immersion experience) or whether one learns to communicate in a second language by learning the lexicogrammar - the words and grammatical structures of the target language. In other words, the argument has been about two different means of achieving the same end.\nAs with any enduring controversy, the matter is not easily resolved. For one thing, there is evidence to support both points of view. It is not uncommon to find learners who, for whatever reason, find themselves in a new country or a new region of their own country, who need to learn a new language, and who do so without the benefit of formal instruction. If they are postpubescent, they may well retain an accent of some kind, but they can pick up enough language to satisfy their communicative needs. In fact, some are natural acquirers who become highly proficient in this manner. In contrast, there are learners whose entire exposure to the new language comes in the form of classroom instruction in lexicogrammar. Yet they too achieve a measure of communicative proficiency, and certain of these learners become highly proficient as well. What we can infer from this is that humans are amazingly versatile learners and that some people have a natural aptitude for acquiring languages and will succeed no matter what the circumstances."
  },
  {
    id: "#99",
    title: "#99 Ecology and Climatology",
    text: "Ecology is the study of interactions of organisms among themselves and with their environment. It seeks to understand patterns in nature (e.g., the spatial and temporal distribution of organisms) and the processes governing those patterns. Climatology is the study of the physical state of the atmosphere its instantaneous state or weather, its seasonal-to-interannual variability, its long-term average condition or climate, and how climate changes over time. These two fields of scientific study are distinctly different. Ecology is a discipline within the biological sciences and has as its core the principle of natural selection. Climatology is a discipline within the geophysical sciences based on applied physics and fluid dynamics. Both, however, share a common history.\nThe origin of these sciences is attributed to Aristotle and Theophrastus and their books Meteorological and Enquiry into Plants, respectively, but their modern beginnings trace back to natural history and plant geography. Seventeenth, eighteenth, and nineteenth century naturalists and geographers saw changes in vegetation as they explored new regions and laid the foundation for the development of ecology and climatology as they sought explanations for these geographic patterns. Alexander von Humboldt, in the early 1800s, observed that widely separated regions have structurally and functionally similar vegetation if their climates are similar. Alphonse de Candolle hypothesized that latitudinal zones of tropical, temperate, and arctic vegetation are caused by temperature and in 1874 proposed formal vegetation zones with associated temperature limits."
  },
  {
    id: "#108",
    title: "#108 Independent Work",
    text: "Working nine to five for a single employer bears little resemblance to the way a substantial share of the workforce makes a living today. Millions of people assemble various income streams and work independently, rather than in structured payroll jobs. This is hardly a new phenomenon, yet it has never been well measured in official statistics and the resulting data gaps prevent a clear view of a large share of labor-market activity. To better understand the independent workforce and what motivates the people who participate in it, the McKinsey Global Institute surveyed some 8,000 respondents across Europe and the United States. We asked about their income in the past 12 months-encompassing primary work, as well as any other income-generating activities, and about their professional satisfaction and aspirations for work in the future. The resulting report, Independent work: Choice, necessity, and the gig economy, finds that up to 162 million people in Europe and the United States - or 20 to 30 percent of the working-age population engage in some form of independent work. While demographically diverse, independent workers largely fit into four segments: free agents, who actively choose independent work and derive their primary income from it; casual earners, who use independent work for supplemental income and do so by choice; reluctants, who make their primary living from independent work but would prefer traditional jobs; and the financially strapped, who do supplemental independent work out of necessity."
  },
  {
    id: "#109",
    title: "#109 Ethics",
    text: "Ethics is a set of moral obligations that define right and wrong in our practices and decisions. Many professions have a formalized system of ethical practices that help guide professionals in the field. For example, doctors commonly take the Hippocratic Oath, which, among other things, states that doctors \"do no harm\" to their patients. Engineers follow an ethical guide that states that they \"hold paramount the safety, health, and welfare of the public.\" Within these professions, as well as within science, the principles become so ingrained that practitioners rarely have to think about adhering to the ethic - it's part of the way they practice. And a breach of ethics is considered very serious, punishable at least within the profession (by revocation of a license, for example) and sometimes by the law as well. Scientific ethics calls for honesty and integrity in all stages of scientific practice, from reporting results regardless to properly attributing collaborators. This system of ethics guides the practice of science, from data collection to publication and beyond. As in other professions, the scientific ethics is deeply integrated into the way scientists work, and they are aware that the reliability of their work and scientific knowledge in general depends upon adhering to that ethic. Many of the ethical principles in science relate to the production of unbiased scientific knowledge, which is critical when others try to build upon or extend research findings. The open publication of data, peer review, replication, and collaboration required by the scientific ethic all help to keep science moving forward by validating research findings and confirming or raising questions about results."
  },
  {
    id: "#129",
    title: "#129 Solar Energy",
    text: "The advantages and disadvantages of solar power compared to other forms of renewable energy have been greatly debated. While obviously superior to some forms of energy, solar power's high cost and efficiency dependent on geography have limited its appeal. However, a large number of advantages also merit further development and even possible adaptation for residences.\nAdvantages of Solar Power\nSolar energy remains popular because it is both a renewable and clean source of energy. These advantages along with the hope that eventually nations can use solar power to decrease global warming ensure its popularity. Solar energy is a true renewable resource. All areas of the world have the ability to collect some amount of solar power and solar power is available for collection each day.\nClean\nSolar energy is non-polluting. It does not create greenhouse gases, such as oil-based energy does, nor does it create waste that must be stored, such as nuclear energy. It is also far more quiet to create and harness, drastically reducing the noise pollution required to convert energy to a useful form. Residential size solar energy systems also have very little impact on the surrounding environment, in contrast with other renewable energy sources such as wind and hydroelectric power.\nLow Maintenance\nSolar panels have no moving parts and require very little maintenance beyond regular cleaning. Without moving parts to break and replace, after the initial costs of installing the panels, maintenance and repair costs are very reasonable."
  },
  {
    id: "#153",
    title: "#153 Importance of Soil",
    text: "It's very easy to forget about what's in the ground beneath our feet and why it's so important to protect it. One tablespoon of soil contains more organisms than there are people on Earth; billions of bacteria, fungi and other microorganisms combine with minerals, water, air and organic matter to create a living system that supports plants and, in turn, all life. Healthy soil can store as much as 3,750 tons of water per hectare, reducing the risk of flooding, and the International Panel on Climate Change (IPCC) has said that 89% of all agricultural emissions could be mitigated if we improved the health of our soil.\nGood soil management also increases disease resistance in livestock and ultimately drives profits for farmers - yet soil and its impact on the health of our animals has, over recent decades, been one of the most neglected links in UK agriculture. Over the last 50 years, agriculture has become increasingly dependent on chemical fertilizers, with applications today around 10 times higher than in the 1950s. Farmers often think the chemical fertilizer NPK (nitrogen, phosphorous and potassium) provides all the nutrition a plant requires, but it also has a detrimental effect on the long-term health of the land: research suggests there are fewer than 100 harvests left in many of the world's soils."
  },
  {
    id: "#80",
    title: "#80 Complaints",
    text: "Humans love to complain to each other. It helps us feel less alone. Think about what happens when a family member or friend is going through a tough time: they call up someone who will listen to their tale of woe. Unfortunately, negative bonding is the default for many groups.\nIn some families, complaining is the only way to get attention. When one person says, I had a bad day; the other person has to top it, \"You think you had a tough day. I had to do three TPS reports!\" The same thing happens at work and social settings. \"Your child didn't sleep through the night until 6 months? Mine was a full year old before she went over six hours.\" It's a race to the bottom, and the worst situation wins.\nIn Bitching is Bonding, A Guide To Mutual Complaint, Irene S. Levine, Ph.D., a professor of psychiatry at the NYU Langone School of Medicine says, \"The reason why these conversations feel good is because we feel understood.\"\nPeople raised in negative environments learn early on. Being positive gets you thrown out of the club. When family dinner is a complaint fest, you're not going to risk alienation saying, \"Wow, I had an awesome day. Don't you just love life?\"\nTranslate this into a work setting: people, often unconsciously, believe being positive keeps you out of the cool club. When negativity provides bonding, humans are reluctant to abandon the behavior that brings them comfort."
  },
  {
    id: "#169",
    title: "#169 Education Technology",
    text: "In 1953 B.F. Skinner visited his daughter's maths class. The Harvard psychologist found every pupil learning the same topic in the same way at the same speed. A few days later he built his first \"teaching machine\", which let children tackle questions at their own pace. By the mid-1960s similar gizmos were being flogged by door-to-door salesmen. Within a few years, though, enthusiasm for them had fizzled out. Since then education technology (edtech) has repeated the cycle of hype and flop, even as computers have reshaped almost every other part of life. One reason is the conservatism of teachers and their unions. But another is that the brain-stretching potential of edtech has remained unproven.\nToday, however, Skinner's heirs are forcing the skeptics to think again. Backed by billionaire techies such as Mark Zuckerberg and Bill Gates, schools around the world are using new software to \"personalize\" learning. This could help hundreds of millions of children stuck in dismal classes but only if edtech boosters can resist the temptation to revive harmful ideas about how children learn. To succeed, edtech must be at the service of teaching, not the other way around.\nThe conventional model of schooling emerged in Prussia in the 18th century. Alternatives have so far failed to teach as many children as efficiently. Classrooms, hierarchical year-groups, standardized curriculums and fixed timetables are still the norm for most of the world's nearly 1.5bn schoolchildren."
  },
  {
    id: "#174",
    title: "#174 Image of Africa",
    text: "Africa is not homogeneous. The negative impression of Africa held internationally is very unfair to those African countries that are actually doing well in their development, because this continent has more than 50 countries rich in natural resources which have not been completely exploited and cultural diversity, and hardworking Africans are struggling to address issues of poverty, disease and war, so Africa can be an attractive place for business development and cultural tourism if concerted international support and assistance are provided. This skewed perception overlooks the vibrant reality and immense potential of the continent.\nAfrica has a lot of potential, and years ago it brought benefits to some companies. Historical engagements have proven that forward-thinking businesses can find success. In fact, Africa is the region with the best investment returns. It is a paradise for investors and adventurers, but it still needs international aid. It is good to do business with Africans because of the mutual money and long-term growth prospects. Furthermore, beyond business, Africa is also beautiful, boasting landscapes and cultural heritage that make it a premier destination for cultural tourism, offering profound experiences for visitors.\nHowever, to discuss Africa honestly, one must also acknowledge its struggles. Africa suffers from frequent wars and the causes are complex, rooted in historical legacies and competition over resources, not in any inherent trait of its people. Africans know what is needed in their development but need assistance in areas like technology transfer, infrastructure financing, and capacity building."
  },
  {
    id: "#189",
    title: "#189 Bank Overdraft",
    text: "Banks provide short-term finance to companies in the form of an overdraft on a current account. The advantage of an overdraft is its flexibility. When the cash needs of the company increase with seasonal factors, the company can continue to write cheques and watch the overdraft increase. When the goods and services are sold and cash begins to flow in, the company should be able to watch the overdraft decrease again. The most obvious example of a business which operates in this pattern is farming. The farmer uses the overdraft to finance the acquisition of seed for arable farming, or feed through the winter for stock farming and to cover the period when the crops or animals are growing and maturing. The overdraft is reduced when the crops or the animals are sold.\nThe main disadvantage of an overdraft is that it is repayable on demand. The farmer whose crop fails because of bad weather knows the problem of being unable to repay the overdraft. Having overdraft financing increases the worries of those who manage the company. The other disadvantage is that the interest payable on overdrafts is variable. When interest rates increase, the cost of the overdraft increases. Furthermore, for small companies there are often complaints that the rate of interest charged is high compared with that available to larger companies. The banks answer that the rates charged reflect relative risk and it is their experience that small companies are more risky."
  },
  {
    id: "#190",
    title: "#190 Deep-sea Mineral Resources",
    text: "The National Oceanography Center (NOC) is engaged in research into the potential risks and benefits of exploiting deep-sea mineral resources, some of which are essential for low-carbon technology, as well as using ocean robots to estimate the environmental impact of these potential deep-sea mining activities. Late last year the NOC led an expedition on the RRS James Cook that found enough of the scarce element Tellurium present in the crust of a submerged volcano that, if it were all to be used in the production of solar PV panels, could provide two-thirds of the UK's annual electricity supply. Recently, the NOC also led an international study demonstrating deep-sea nodule mining will cause long-lasting damage to deep-sea life, lasting at least for decades.\nThese nodules are potato-sized rocks containing high levels of metals, including copper, manganese and nickel. They grow very slowly on the sea-bed, over millions of years. Although no commercial operations exist to extract these resources, many are planned.\nProfessor Edward Hill, Executive Director at the NOC commented, \"By 2050 there will be nine billion people on earth and attention is increasingly turning to the ocean, particularly the deep ocean, for food, clean supplies of energy and strategic minerals. The NOC is undertaking research related to many aspects and perspectives involved in exploiting ocean resources. This research is aimed at informing with sound scientific evidence the decisions that will need to be taken in the future, as people increasingly turn to the oceans to address some of society's greatest challenges.\""
  },
  {
    id: "#192",
    title: "#192 Volcano Prediction",
    text: "In general, no single event can be used to predict a volcanic eruption, and thus many events are usually monitored so that taken in total, an eruption can often be predicted. Still, each volcano behaves somewhat differently, and until patterns are recognized for an individual volcano, predictions vary in their reliability. Furthermore, sometimes a volcano can erupt with no precursor events at all.\nAfter the catastrophic eruption of Mount St. Helens on May 18, 1980, a volcanic dome began to grow in the crater. Growth of this dome occurred sporadically, and sometimes small eruptions occurred from the dome. After several years of dedicated monitoring, scientists are now able to predict with increasing accuracy eruptions from this dome. An example is shown in the graphs to the right. In the weeks prior to an eruption on March 19, 1982, the amount of seismic energy released increased, the amount of dome expansion increased, tilt increased, and SO2 emissions increased prior to the event.\nNote that eruption predictions are only possible if constant monitoring of a volcano takes place. Monitoring is an expensive endeavor, and not all active or potentially active volcanoes are monitored. Still, if people living around volcanoes are aware of some of the precursor phenomena they may be able to communicate their findings to scientists and help prevent a pending disaster."
  },
  {
    id: "#206",
    title: "#206 Summer Vacation",
    text: "There are few things U.S. students love more than summer vacation, that traditionally three-month break from school during June, July and August. But why does it even exist?\nA common theory holds that summer vacation was created for farm kids who needed to work. That's only marginally true: students at rural schools did get time off for harvests, but those breaks fell in the spring and the fall.\nIn fact, summer vacation was born in the city. Calls for a break began in the mid-19th century, when many urban schools met year-round. Warnings about \"overstudy\" led reformers like Horace Mann to argue that time off would be good for kids' behavior and mental health, says Kenneth M. Gold, author of \"The History of Summer Education\" in American Public Schools. John C. Warren, a Harvard professor of anatomy and surgery, once remarked that \"too steady an application to literary pursuits led to a 'debilitated body'\". And in an era before AC, experts worried that poorly ventilated school buildings compounded the risks.\nDebate raged for decades. But as railroads made nature more accessible for city dwellers, wealthier parents increasingly took matters into their own hands and took their kids out of school. Eventually, the vacationers won out, and the break became official.\nNowadays, reformers have changed their tune: they argue that eliminating long summer vacations could shrink achievement gaps between students. It's an idea backed up by data but one at which their forebears might shudder."
  },
  {
    id: "#215",
    title: "#215 South Africa",
    text: "The area that is now South Africa has been inhabited by humans for millennia. The San, the original inhabitants of this land, were migratory people who lived in small groups of about 15 to 20 people. They survived by fishing and hunting and by gathering roots and other wild foods. They did not build permanent dwellings but used rock shelters as temporary dwellings. Around 2,000 years ago Khoikhoi pastoralists migrated to the coast.\nIn the eastern part of present-day South Africa, iron-working societies date from about 300 A.D. The Sotho-Tswana and Nguni peoples arrived in this region around 1,200 A.D. They lived by agriculture and stock farming, mined gold, copper and tin and hunted for ivory and built stone-walled towns. Over the centuries, these societies had diverse contacts with the Khoisan. Strife between the San and the Khoikhoi developed over competition for game; eventually the Khoikhoi became dominant. These people lived in the western part of present-day South Africa and are known collectively as the Khoisan."
  },
  {
    id: "#230",
    title: "#230 Natural Language",
    text: "When people start thinking about language, the first question which often occurs to them is this: is language natural to humans? - in the same way that grunting is natural to pigs, and barking comes naturally to dogs. Or is it just something we happen to have learned? - in the same way that dogs may learn to beg, or elephants may learn to waltz, or humans may learn to play the guitar.\nClearly, in one sense, children 'learn' whatever language they are exposed to, be it Chinese, Nootka or English. So no one would deny that 'learning' is very important. But the crucial question is whether children are born with 'blank sheets' in their head as far as language is concerned or whether humans are 'programmed' with an outline knowledge of the structure of languages in general.\nThis question of whether language is partly due to nature or wholly due to learning or nurture is often referred to as the nature-nurture controversy, and has been discussed for centuries. For example, it was the topic of one of Plato's dialogues, the Cratylus. Controversies which have been going on for literally ages tend to behave in a characteristic fashion. They lie dormant for a while, then break out fiercely. This particular issue resurfaced in linguistics in 1959 when the linguist Noam Chomsky wrote a devastating and witty review of Verbal Behavior, a book by the Harvard psychologist B.F. Skinner (Skinner 1957; Chomsky 1959). This book claimed to 'explain' language as a set of habits gradually built up over the years. According to Skinner, no complicated innate or mental mechanisms are needed. All that is necessary is the systematic observation of the events in the external world which prompt the speaker to utter sounds."
  },
  {
    id: "#257",
    title: "#257 Prior Knowledge",
    text: "What is known as prior knowledge (or pre-existing knowledge) is the knowledge, skill or ability that a learner brings to a new learning encounter. This includes all knowledge that is available before the learning event, and which has been gathered or developed by any means, and in any situation, including both formal and, quite often, informal learning situations. Learners need enough previous knowledge and understanding to enable them to learn new things; they also need help making links with new and previous explicit knowledge.\nIt is considered to be valuable to go through a process of what has been called \"activating prior knowledge\". Teachers often go through this process at the beginning of a new topic. They also use introductory strategies at the beginning of lessons which are continuations from previous lessons. In terms of the practicalities of teaching, this is a process of making children think about the topic or remember what has been covered already. In terms of theory, it is to do with activating particular schemas."
  },
  {
    id: "#336",
    title: "#336 Difference in Intelligence",
    text: "People differ greatly in all aspects of what is casually known as intelligence. The differences are apparent not only in school, from kindergarten to college, but also in the most ordinary circumstances: in the words people use and comprehend, in their differing abilities to read a map or follow directions, or in their capacities for remembering telephone numbers or figuring change. The variations in these specific skills are so common that they are often taken for granted. Yet what makes people so different?\nIt would be reasonable to think that the environment is the source of differences in cognitive skills that we are what we learn. It is clear, for example, that human beings are not born with a full vocabulary; they have to learn words. Hence, learning must be the mechanism by which differences in vocabulary arise among individuals. And differences in experience say, in the extent to which parents model and encourage vocabulary skills or in the quality of language training provided by schools must be responsible for individual differences in learning.\nEarlier in this century, psychology was in fact dominated by environmental explanations for variance in cognitive abilities. More recently, however, most psychologists have begun to embrace a more balanced view: one in which nature and nurture interact in cognitive development. During the past few decades, studies in genetics have pointed to a substantial role for heredity in molding the components of intellect, and researchers have even begun to track down the genes involved in cognitive function. These findings do not refute the notion that environmental factors shape the learning process. Instead they suggest that differences in people's genes affect how easily they learn."
  },
  {
    id: "#416",
    title: "#416 Immune System",
    text: "The immune system is a complex network of different organs, cells, and proteins that work together. There are 2 main parts of the immune system: the innate immune system - you are born with this, and the adaptive immune system you develop this when your body is exposed to microbes or chemicals released by microbes. These two immune systems work together.\nThe innate immune system is your child's rapid response system. It is the first to respond when it finds an invader. It is made up of the skin, the eye's cornea, and the mucous membrane that lines the respiratory, gastrointestinal, and genitourinary tracts. These all create physical barriers to help protect your child's body. They protect against harmful germs, parasites (such as worms), or cells (such as cancer). The innate immune system is inherited. It is active from the moment your child is born. When this system recognizes an invader, it goes into action right away. The cells of this immune system surround and cover the invader. The invader is killed inside the immune system cells (called phagocytes).\nThe acquired immune system, with help from the innate system, makes special proteins (called antibodies) to protect your body from a specific invader. These antibodies are developed by cells called B lymphocytes after the body has been exposed to the invader. The antibodies stay in your child's body. It can take several days for antibodies to form. But after the first exposure, the immune system will recognize the invader and defend against it. The acquired immune system changes during your child's life. Immunizations train your child's immune system to make antibodies to protect them from harmful diseases."
  },
  {
    id: "#482",
    title: "#482 Electric Cars(C)",
    text: "Although electric cars were clean, quiet, and simple to operate, the drawback then, as now, was their limited range and long charging time. After 1915, they fell out of vogue as cars powered by internal-combustion engines and fueled with cheap gasoline gained favor.\nAs concerns in recent years have grown about global warming caused by carbon-dioxide emissions, scientists have begun to reconsider electricity as a fuel for vehicles. But today's drivers (U.S. consumers, based on the article's U.S.-centered context) expect a vehicle that is fuel efficient, and a fuel that is readily available in numerous locations and allows instant refueling.\nAlthough electric cars are fairly efficient, they require frequent refueling, and the process is far from instantaneous. They are expensive, too, since normal use causes their US$2,000 lead-acid batteries to wear out in just a few years. And, ironically, electric cars do very little to reduce carbon dioxide emissions, because most U.S. electricity is generated by burning coal and other fossil fuels.\nTo gain U.S. consumer acceptance, the car of the future will need to balance the benefits of electric cars with U.S. consumers' demands for distance and dynamo. The hybrid electric vehicle holds promise as a solution to both these needs."
  },
  {
    id: "#503",
    title: "#503 Triangulation",
    text: "While multi-method research is experiencing a surge of popularity, there are reasons to worry about whether multi-method applications are producing more grounded, justified, and persuasive inferences than single-method studies. These concerns arise from the 'triangulation' framework as prototypical research design for multi-method social science. Simply put, triangulation designs involve asking the same causal inference question using two different methods, checking same substantive conclusions. The metaphor is to the geometric technique of estimating distance by measuring the angle of sight toward an object from two different vantage points.\nTriangulation in social sciences has major flaws. One is well-known and widely discussed: what conclusion should be drawn when the two methods produce different findings? Unfortunately, the list of intellectually plausible responses to such an outcome is all but unbounded.\nFor example, a scholar could reasonably conclude that both findings are correct but capture different aspects of the phenomenon of interest; that one method or the other displayed fundamental limitations in the analysis; that the divergence provides evidence against the credibility of the assumptions involved in both methods; that the outcome involves a contrast in terms of scope or relevant populations for the two methods; or that the failure to triangulate simply leaves the inference in a state of uncertainty. In decades of writing about triangulation, no definitive guidance has yet emerged about how to respond to divergent findings between the multiple methods in a study."
  }
];
